"""
Historical Formula 1 data (1950-2025).
Compact dataset with real champions and top drivers per season.
Ratings 60-100 are derived from real historical performance.
"""

# Format per season:
# year: {
#   "champion": str, "champion_team": str,
#   "constructors_champion": str,
#   "num_races": int,
#   "drivers": [ (name, team, rating), ... ]  # top ~10-14 drivers
# }

def _D(*args):
    return [(n, t, r) for n, t, r in args]

SEASONS = {
    1950: {"champion": "Giuseppe Farina", "champion_team": "Alfa Romeo", "constructors_champion": "Alfa Romeo", "num_races": 7,
        "drivers": _D(("Giuseppe Farina","Alfa Romeo",95),("Juan Manuel Fangio","Alfa Romeo",96),("Luigi Fagioli","Alfa Romeo",88),("Reg Parnell","Alfa Romeo",80),("Alberto Ascari","Ferrari",92),("Luigi Villoresi","Ferrari",83),("Raymond Sommer","Ferrari",82),("Dorino Serafini","Ferrari",76),("Louis Rosier","Talbot-Lago",78),("Philippe Etancelin","Talbot-Lago",74),("Yves Giraud-Cabantous","Talbot-Lago",72),("Eugene Chaboud","Talbot-Lago",68),("Louis Chiron","Maserati",72),("Emmanuel de Graffenried","Maserati",73),("Prince Bira","Maserati",70),("Franco Rol","Maserati",66),("Robert Manzon","Simca-Gordini",76),("Maurice Trintignant","Simca-Gordini",76),("Johnnie Parsons","Kurtis Kraft",76),("Bill Holland","Deidt",74))},
    1951: {"champion": "Juan Manuel Fangio", "champion_team": "Alfa Romeo", "constructors_champion": "Ferrari", "num_races": 8,
        "drivers": _D(("Juan Manuel Fangio","Alfa Romeo",97),("Giuseppe Farina","Alfa Romeo",90),("Felice Bonetto","Alfa Romeo",76),("Consalvo Sanesi","Alfa Romeo",74),("Alberto Ascari","Ferrari",93),("Froilan Gonzalez","Ferrari",86),("Luigi Villoresi","Ferrari",82),("Piero Taruffi","Ferrari",80),("Reg Parnell","BRM",74),("Peter Walker","BRM",70),("Louis Rosier","Talbot-Lago",70),("Louis Chiron","Talbot-Lago",68),("Philippe Etancelin","Talbot-Lago",66),("Yves Giraud-Cabantous","Talbot-Lago",68),("Emmanuel de Graffenried","Maserati",72),("Prince Bira","Maserati",70),("Kenneth McAlpine","Connaught",64),("Andre Simon","Simca-Gordini",70),("Lee Wallard","Kurtis Kraft",76),("Bill Vukovich","Kurtis Kraft",78))},
    1952: {"champion": "Alberto Ascari", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 8,
        "drivers": _D(("Alberto Ascari","Ferrari",98),("Giuseppe Farina","Ferrari",90),("Piero Taruffi","Ferrari",84),("Luigi Villoresi","Ferrari",82),("Andre Simon","Ferrari",74),("Rudi Fischer","Ferrari",72),("Froilan Gonzalez","Maserati",85),("Felice Bonetto","Maserati",75),("Emmanuel de Graffenried","Maserati",70),("Robert Manzon","Gordini",76),("Maurice Trintignant","Gordini",76),("Jean Behra","Gordini",78),("Mike Hawthorn","Cooper",82),("Peter Collins","HWM",78),("Lance Macklin","HWM",72),("Paul Frere","HWM",70),("Dennis Poore","Connaught",68),("Ken Downing","Connaught",64),("Ken Wharton","Frazer Nash",66),("Bill Vukovich","Kurtis Kraft",80))},
    1953: {"champion": "Alberto Ascari", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 9,
        "drivers": _D(("Alberto Ascari","Ferrari",97),("Giuseppe Farina","Ferrari",90),("Mike Hawthorn","Ferrari",85),("Luigi Villoresi","Ferrari",82),("Piero Taruffi","Ferrari",80),("Juan Manuel Fangio","Maserati",94),("Froilan Gonzalez","Maserati",84),("Onofre Marimon","Maserati",76),("Felice Bonetto","Maserati",74),("Emmanuel de Graffenried","Maserati",72),("Louis Rosier","Ferrari",70),("Sergio Mantovani","Maserati",72),("Jean Behra","Gordini",78),("Robert Manzon","Gordini",76),("Maurice Trintignant","Gordini",76),("Harry Schell","Gordini",74),("Ken Wharton","Cooper",68),("Stirling Moss","Connaught",90),("Bill Vukovich","Kurtis Kraft",82),("Jimmy Bryan","Kuzma",72))},
    1954: {"champion": "Juan Manuel Fangio", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 9,
        "drivers": _D(("Juan Manuel Fangio","Mercedes",98),("Karl Kling","Mercedes",80),("Hans Herrmann","Mercedes",76),("Stirling Moss","Mercedes",93),("Froilan Gonzalez","Ferrari",87),("Mike Hawthorn","Ferrari",84),("Maurice Trintignant","Ferrari",78),("Giuseppe Farina","Ferrari",84),("Robert Manzon","Ferrari",74),("Roberto Mieres","Maserati",74),("Luigi Musso","Maserati",78),("Sergio Mantovani","Maserati",72),("Onofre Marimon","Maserati",76),("Prince Bira","Maserati",70),("Harry Schell","Maserati",76),("Jean Behra","Gordini",80),("Andre Pilette","Gordini",70),("Bill Vukovich","Kurtis Kraft",82),("Jimmy Bryan","Kuzma",74),("Peter Collins","Vanwall",84))},
    1955: {"champion": "Juan Manuel Fangio", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 7,
        "drivers": _D(("Juan Manuel Fangio","Mercedes",99),("Stirling Moss","Mercedes",94),("Karl Kling","Mercedes",80),("Piero Taruffi","Mercedes",78),("Hans Herrmann","Mercedes",76),("Alberto Ascari","Lancia",92),("Eugenio Castellotti","Lancia",80),("Luigi Villoresi","Lancia",78),("Giuseppe Farina","Ferrari",82),("Maurice Trintignant","Ferrari",78),("Mike Hawthorn","Ferrari",84),("Nino Farina","Ferrari",80),("Roberto Mieres","Maserati",74),("Luigi Musso","Maserati",78),("Jean Behra","Maserati",81),("Cesare Perdisa","Maserati",72),("Harry Schell","Vanwall",76),("Ken Wharton","Vanwall",70),("Bob Sweikert","Kurtis Kraft",74),("Jimmy Bryan","Kuzma",72))},
    1956: {"champion": "Juan Manuel Fangio", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 8,
        "drivers": _D(("Juan Manuel Fangio","Ferrari",97),("Peter Collins","Ferrari",85),("Eugenio Castellotti","Ferrari",80),("Alfonso de Portago","Ferrari",76),("Luigi Musso","Ferrari",82),("Paul Frere","Ferrari",74),("Olivier Gendebien","Ferrari",76),("Stirling Moss","Maserati",95),("Jean Behra","Maserati",82),("Cesare Perdisa","Maserati",72),("Harry Schell","Vanwall",78),("Maurice Trintignant","Vanwall",78),("Colin Chapman","Vanwall",70),("Mike Hawthorn","BRM",84),("Tony Brooks","BRM",84),("Roy Salvadori","Maserati",74),("Francisco Godia","Maserati",70),("Louis Rosier","Maserati",66),("Pat Flaherty","Watson",76),("Sam Hanks","Kurtis Kraft",76))},
    1957: {"champion": "Juan Manuel Fangio", "champion_team": "Maserati", "constructors_champion": "Maserati", "num_races": 8,
        "drivers": _D(("Juan Manuel Fangio","Maserati",99),("Jean Behra","Maserati",82),("Harry Schell","Maserati",78),("Carlos Menditeguy","Maserati",70),("Giorgio Scarlatti","Maserati",68),("Stirling Moss","Vanwall",95),("Tony Brooks","Vanwall",84),("Stuart Lewis-Evans","Vanwall",80),("Mike Hawthorn","Ferrari",86),("Luigi Musso","Ferrari",83),("Peter Collins","Ferrari",82),("Alfonso de Portago","Ferrari",74),("Wolfgang von Trips","Ferrari",82),("Maurice Trintignant","Ferrari",76),("Roy Salvadori","BRM",76),("Jack Brabham","Cooper",80),("Ron Flockhart","BRM",70),("Carroll Shelby","Maserati",72),("Sam Hanks","Salih",74),("Jim Rathmann","Epperly",72))},
    1958: {"champion": "Mike Hawthorn", "champion_team": "Ferrari", "constructors_champion": "Vanwall", "num_races": 11,
        "drivers": _D(("Mike Hawthorn","Ferrari",92),("Peter Collins","Ferrari",84),("Luigi Musso","Ferrari",83),("Wolfgang von Trips","Ferrari",82),("Phil Hill","Ferrari",85),("Olivier Gendebien","Ferrari",76),("Stirling Moss","Vanwall",96),("Tony Brooks","Vanwall",88),("Stuart Lewis-Evans","Vanwall",81),("Harry Schell","BRM",78),("Jean Behra","BRM",80),("Ron Flockhart","BRM",72),("Roy Salvadori","Cooper",82),("Jack Brabham","Cooper",84),("Bruce McLaren","Cooper",80),("Maurice Trintignant","Cooper",80),("Cliff Allison","Lotus",76),("Graham Hill","Lotus",82),("Jim Rathmann","Epperly",74),("Jimmy Bryan","Epperly",74))},
    1959: {"champion": "Jack Brabham", "champion_team": "Cooper", "constructors_champion": "Cooper", "num_races": 9,
        "drivers": _D(("Jack Brabham","Cooper",92),("Bruce McLaren","Cooper",83),("Masten Gregory","Cooper",78),("Maurice Trintignant","Cooper",78),("Stirling Moss","Cooper",95),("Roy Salvadori","Aston Martin",78),("Carroll Shelby","Aston Martin",74),("Tony Brooks","Ferrari",89),("Phil Hill","Ferrari",86),("Dan Gurney","Ferrari",81),("Jean Behra","Ferrari",80),("Cliff Allison","Ferrari",76),("Olivier Gendebien","Ferrari",74),("Harry Schell","BRM",78),("Jo Bonnier","BRM",78),("Ron Flockhart","BRM",70),("Graham Hill","Lotus",83),("Innes Ireland","Lotus",78),("Jim Rathmann","Watson",74),("Rodger Ward","Watson",72))},
    1960: {"champion": "Jack Brabham", "champion_team": "Cooper", "constructors_champion": "Cooper", "num_races": 10,
        "drivers": _D(("Jack Brabham","Cooper",94),("Bruce McLaren","Cooper",87),("Olivier Gendebien","Cooper",76),("Henry Taylor","Cooper",70),("Stirling Moss","Lotus",96),("Innes Ireland","Lotus",81),("Jim Clark","Lotus",89),("John Surtees","Lotus",84),("Alan Stacey","Lotus",72),("Phil Hill","Ferrari",86),("Wolfgang von Trips","Ferrari",84),("Willy Mairesse","Ferrari",76),("Richie Ginther","Ferrari",80),("Graham Hill","BRM",83),("Dan Gurney","BRM",84),("Jo Bonnier","BRM",78),("Harry Schell","BRM",76),("Roy Salvadori","Aston Martin",76),("Jim Rathmann","Watson",74),("Rodger Ward","Watson",70))},
    1961: {"champion": "Phil Hill", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 8,
        "drivers": _D(("Phil Hill","Ferrari",93),("Wolfgang von Trips","Ferrari",89),("Richie Ginther","Ferrari",82),("Giancarlo Baghetti","Ferrari",80),("Willy Mairesse","Ferrari",76),("Stirling Moss","Lotus",95),("Jim Clark","Lotus",90),("Innes Ireland","Lotus",78),("Trevor Taylor","Lotus",72),("Dan Gurney","Porsche",84),("Jo Bonnier","Porsche",78),("Hans Herrmann","Porsche",70),("Jack Brabham","Cooper",88),("Bruce McLaren","Cooper",85),("Roy Salvadori","Cooper",74),("Graham Hill","BRM",82),("Tony Brooks","BRM",82),("John Surtees","Cooper",83),("Masten Gregory","Cooper",74),("Henry Taylor","Cooper",68))},
    1962: {"champion": "Graham Hill", "champion_team": "BRM", "constructors_champion": "BRM", "num_races": 9,
        "drivers": _D(("Graham Hill","BRM",92),("Richie Ginther","BRM",80),("Tony Maggs","Cooper",78),("Jim Clark","Lotus",95),("Trevor Taylor","Lotus",76),("Innes Ireland","Lotus",76),("Bruce McLaren","Cooper",86),("Jack Brabham","Brabham",88),("Dan Gurney","Porsche",83),("Jo Bonnier","Porsche",78),("Phil Hill","Ferrari",85),("Lorenzo Bandini","Ferrari",78),("Giancarlo Baghetti","Ferrari",78),("Ricardo Rodriguez","Ferrari",78),("Willy Mairesse","Ferrari",76),("John Surtees","Lola",84),("Roy Salvadori","Lola",74),("Masten Gregory","Lotus",74),("Maurice Trintignant","Lotus",72),("Ronnie Bucknum","Honda",70))},
    1963: {"champion": "Jim Clark", "champion_team": "Lotus", "constructors_champion": "Lotus", "num_races": 10,
        "drivers": _D(("Jim Clark","Lotus",99),("Trevor Taylor","Lotus",76),("Peter Arundell","Lotus",74),("Mike Hailwood","Lotus",72),("Graham Hill","BRM",90),("Richie Ginther","BRM",82),("Ludovico Scarfiotti","Ferrari",76),("John Surtees","Ferrari",87),("Lorenzo Bandini","Ferrari",80),("Willy Mairesse","Ferrari",74),("Dan Gurney","Brabham",84),("Jack Brabham","Brabham",85),("Bruce McLaren","Cooper",83),("Tony Maggs","Cooper",76),("Jo Bonnier","Cooper",76),("Innes Ireland","BRP",74),("Jim Hall","Lotus",72),("Chris Amon","Lola",82),("Mario Cabral","ATS",68),("Phil Hill","ATS",82))},
    1964: {"champion": "John Surtees", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 10,
        "drivers": _D(("John Surtees","Ferrari",93),("Lorenzo Bandini","Ferrari",81),("Ludovico Scarfiotti","Ferrari",76),("Graham Hill","BRM",92),("Richie Ginther","BRM",80),("Jim Clark","Lotus",96),("Peter Arundell","Lotus",78),("Mike Spence","Lotus",76),("Walt Hansgen","Lotus",70),("Dan Gurney","Brabham",85),("Jack Brabham","Brabham",84),("Denny Hulme","Brabham",82),("Bruce McLaren","Cooper",83),("Phil Hill","Cooper",82),("Jo Bonnier","Cooper",74),("Chris Amon","Lotus",80),("Innes Ireland","BRP",74),("Jo Siffert","Brabham",74),("Trevor Taylor","BRP",72),("Ronnie Bucknum","Honda",70))},
    1965: {"champion": "Jim Clark", "champion_team": "Lotus", "constructors_champion": "Lotus", "num_races": 10,
        "drivers": _D(("Jim Clark","Lotus",99),("Mike Spence","Lotus",76),("Graham Hill","BRM",91),("Jackie Stewart","BRM",89),("Richie Ginther","Honda",78),("Ronnie Bucknum","Honda",70),("John Surtees","Ferrari",87),("Lorenzo Bandini","Ferrari",80),("Ludovico Scarfiotti","Ferrari",76),("Dan Gurney","Brabham",85),("Jack Brabham","Brabham",84),("Denny Hulme","Brabham",83),("Bruce McLaren","Cooper",82),("Jochen Rindt","Cooper",84),("Jo Bonnier","Cooper",74),("Jo Siffert","Brabham",76),("Frank Gardner","Brabham",70),("Bob Anderson","Brabham",68),("Innes Ireland","Lotus",73),("Masten Gregory","Cooper",72))},
    1966: {"champion": "Jack Brabham", "champion_team": "Brabham", "constructors_champion": "Brabham", "num_races": 9,
        "drivers": _D(("Jack Brabham","Brabham",92),("Denny Hulme","Brabham",86),("Jim Clark","Lotus",94),("Peter Arundell","Lotus",74),("Pedro Rodriguez","Lotus",78),("Graham Hill","BRM",88),("Jackie Stewart","BRM",89),("Bob Bondurant","BRM",68),("John Surtees","Ferrari",86),("Lorenzo Bandini","Ferrari",80),("Mike Parkes","Ferrari",78),("Ludovico Scarfiotti","Ferrari",76),("Dan Gurney","Eagle",84),("Richie Ginther","Cooper",76),("Jochen Rindt","Cooper",84),("Chris Amon","Cooper",80),("Jo Bonnier","Cooper",74),("Jo Siffert","Cooper",74),("John Taylor","Brabham",68),("Bruce McLaren","McLaren",82))},
    1967: {"champion": "Denny Hulme", "champion_team": "Brabham", "constructors_champion": "Brabham", "num_races": 11,
        "drivers": _D(("Denny Hulme","Brabham",90),("Jack Brabham","Brabham",89),("Jim Clark","Lotus",96),("Graham Hill","Lotus",88),("Chris Amon","Ferrari",85),("Lorenzo Bandini","Ferrari",80),("Mike Parkes","Ferrari",76),("Ludovico Scarfiotti","Ferrari",74),("Jackie Stewart","BRM",90),("Mike Spence","BRM",76),("John Surtees","Honda",84),("Dan Gurney","Eagle",82),("Jo Siffert","Cooper",78),("Pedro Rodriguez","Cooper",81),("Jochen Rindt","Cooper",84),("Richie Ginther","Eagle",74),("Bruce McLaren","McLaren",82),("Chris Irwin","BRM",70),("Alan Rees","Cooper",68),("Guy Ligier","Cooper",70))},
    1968: {"champion": "Graham Hill", "champion_team": "Lotus", "constructors_champion": "Lotus", "num_races": 12,
        "drivers": _D(("Graham Hill","Lotus",90),("Jim Clark","Lotus",95),("Jo Siffert","Lotus",78),("Jackie Oliver","Lotus",76),("Jackie Stewart","Matra",93),("Jean-Pierre Beltoise","Matra",78),("Johnny Servoz-Gavin","Matra",74),("Jacky Ickx","Ferrari",84),("Chris Amon","Ferrari",83),("Derek Bell","Ferrari",76),("Denny Hulme","McLaren",86),("Bruce McLaren","McLaren",84),("Dan Gurney","McLaren",80),("Pedro Rodriguez","BRM",80),("Richard Attwood","BRM",74),("John Surtees","Honda",82),("Jack Brabham","Brabham",85),("Jochen Rindt","Brabham",86),("Silvio Moser","Brabham",68),("Piers Courage","BRM",78))},
    1969: {"champion": "Jackie Stewart", "champion_team": "Matra", "constructors_champion": "Matra", "num_races": 11,
        "drivers": _D(("Jackie Stewart","Matra",97),("Jean-Pierre Beltoise","Matra",80),("Johnny Servoz-Gavin","Matra",74),("Jochen Rindt","Lotus",90),("Graham Hill","Lotus",85),("Mario Andretti","Lotus",84),("Richard Attwood","Lotus",74),("Jacky Ickx","Brabham",87),("Jack Brabham","Brabham",85),("Piers Courage","Brabham",80),("Denny Hulme","McLaren",84),("Bruce McLaren","McLaren",83),("Derek Bell","McLaren",72),("Chris Amon","Ferrari",82),("Pedro Rodriguez","Ferrari",79),("John Surtees","BRM",81),("Jackie Oliver","BRM",76),("Jo Siffert","Lotus",78),("Vic Elford","McLaren",70),("Silvio Moser","Brabham",68))},
    1970: {"champion": "Jochen Rindt", "champion_team": "Lotus", "constructors_champion": "Lotus", "num_races": 13,
        "drivers": _D(("Jochen Rindt","Lotus",96),("Emerson Fittipaldi","Lotus",85),("John Miles","Lotus",74),("Reine Wisell","Lotus",76),("Jacky Ickx","Ferrari",89),("Clay Regazzoni","Ferrari",84),("Ignazio Giunti","Ferrari",76),("Jackie Stewart","Tyrrell",94),("Francois Cevert","Tyrrell",80),("Denny Hulme","McLaren",83),("Bruce McLaren","McLaren",84),("Dan Gurney","McLaren",78),("Peter Gethin","McLaren",74),("Jack Brabham","Brabham",85),("Rolf Stommelen","Brabham",76),("Chris Amon","March",82),("Jo Siffert","March",79),("Jean-Pierre Beltoise","Matra",78),("Henri Pescarolo","Matra",76),("Pedro Rodriguez","BRM",80))},
    1971: {"champion": "Jackie Stewart", "champion_team": "Tyrrell", "constructors_champion": "Tyrrell", "num_races": 11,
        "drivers": _D(("Jackie Stewart","Tyrrell",98),("Francois Cevert","Tyrrell",83),("Ronnie Peterson","March",84),("Mike Beuttler","March",70),("Jacky Ickx","Ferrari",87),("Clay Regazzoni","Ferrari",82),("Mario Andretti","Ferrari",84),("Emerson Fittipaldi","Lotus",86),("Reine Wisell","Lotus",76),("Denny Hulme","McLaren",82),("Peter Gethin","BRM",80),("Jo Siffert","BRM",80),("Howden Ganley","BRM",74),("Pedro Rodriguez","BRM",80),("Chris Amon","Matra",81),("Jean-Pierre Beltoise","Matra",78),("Henri Pescarolo","March",76),("Tim Schenken","Brabham",76),("Graham Hill","Brabham",82),("Rolf Stommelen","Surtees",76))},
    1972: {"champion": "Emerson Fittipaldi", "champion_team": "Lotus", "constructors_champion": "Lotus", "num_races": 12,
        "drivers": _D(("Emerson Fittipaldi","Lotus",95),("Dave Walker","Lotus",70),("Jackie Stewart","Tyrrell",94),("Francois Cevert","Tyrrell",82),("Jacky Ickx","Ferrari",85),("Clay Regazzoni","Ferrari",82),("Mario Andretti","Ferrari",84),("Denny Hulme","McLaren",83),("Peter Revson","McLaren",81),("Brian Redman","McLaren",76),("Ronnie Peterson","March",84),("Niki Lauda","March",82),("Chris Amon","Matra",80),("Jean-Pierre Beltoise","BRM",78),("Howden Ganley","BRM",74),("Reine Wisell","BRM",72),("Mike Hailwood","Surtees",78),("Tim Schenken","Surtees",74),("Graham Hill","Brabham",80),("Wilson Fittipaldi","Brabham",74))},
    1973: {"champion": "Jackie Stewart", "champion_team": "Tyrrell", "constructors_champion": "Lotus", "num_races": 15,
        "drivers": _D(("Jackie Stewart","Tyrrell",97),("Francois Cevert","Tyrrell",84),("Chris Amon","Tyrrell",80),("Emerson Fittipaldi","Lotus",93),("Ronnie Peterson","Lotus",90),("Peter Revson","McLaren",83),("Denny Hulme","McLaren",82),("Jody Scheckter","McLaren",84),("Jacky Ickx","Ferrari",82),("Arturo Merzario","Ferrari",76),("Carlos Reutemann","Brabham",84),("Wilson Fittipaldi","Brabham",74),("Andrea de Adamich","Brabham",70),("James Hunt","March",83),("Jean-Pierre Jarier","March",78),("Mike Hailwood","Surtees",78),("Carlos Pace","Surtees",83),("Jean-Pierre Beltoise","BRM",78),("Niki Lauda","BRM",84),("Clay Regazzoni","BRM",80))},
    1974: {"champion": "Emerson Fittipaldi", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 15,
        "drivers": _D(("Emerson Fittipaldi","McLaren",94),("Denny Hulme","McLaren",81),("Mike Hailwood","McLaren",78),("Clay Regazzoni","Ferrari",88),("Niki Lauda","Ferrari",91),("Ronnie Peterson","Lotus",87),("Jacky Ickx","Lotus",82),("Jody Scheckter","Tyrrell",89),("Patrick Depailler","Tyrrell",82),("Carlos Reutemann","Brabham",85),("Carlos Pace","Brabham",82),("Rikky von Opel","Brabham",70),("James Hunt","Hesketh",84),("Vittorio Brambilla","March",78),("Hans-Joachim Stuck","March",76),("Jean-Pierre Jarier","Shadow",78),("Tom Pryce","Shadow",76),("Jean-Pierre Beltoise","BRM",76),("Chris Amon","BRM",78),("Arturo Merzario","Iso Marlboro",74))},
    1975: {"champion": "Niki Lauda", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 14,
        "drivers": _D(("Niki Lauda","Ferrari",96),("Clay Regazzoni","Ferrari",85),("Emerson Fittipaldi","McLaren",91),("Jochen Mass","McLaren",80),("Carlos Reutemann","Brabham",85),("Carlos Pace","Brabham",83),("Ronnie Peterson","Lotus",86),("Jacky Ickx","Lotus",80),("Jody Scheckter","Tyrrell",88),("Patrick Depailler","Tyrrell",81),("James Hunt","Hesketh",86),("Vittorio Brambilla","March",78),("Lella Lombardi","March",70),("Tom Pryce","Shadow",78),("Jean-Pierre Jarier","Shadow",76),("Mario Andretti","Parnelli",84),("Mark Donohue","Penske",78),("John Watson","Surtees",80),("Alan Jones","Hesketh",82),("Arturo Merzario","Williams",72))},
    1976: {"champion": "James Hunt", "champion_team": "McLaren", "constructors_champion": "Ferrari", "num_races": 16,
        "drivers": _D(("James Hunt","McLaren",93),("Jochen Mass","McLaren",80),("Niki Lauda","Ferrari",95),("Clay Regazzoni","Ferrari",83),("Carlos Reutemann","Ferrari",84),("Jody Scheckter","Tyrrell",88),("Patrick Depailler","Tyrrell",84),("Mario Andretti","Lotus",86),("Ronnie Peterson","Lotus",85),("Gunnar Nilsson","Lotus",78),("Emerson Fittipaldi","Copersucar",86),("John Watson","Penske",82),("Tom Pryce","Shadow",76),("Jean-Pierre Jarier","Shadow",76),("Jacques Laffite","Ligier",82),("Vittorio Brambilla","March",76),("Hans-Joachim Stuck","March",76),("Alan Jones","Surtees",82),("Carlos Pace","Brabham",82),("Chris Amon","Ensign",78))},
    1977: {"champion": "Niki Lauda", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 17,
        "drivers": _D(("Niki Lauda","Ferrari",95),("Carlos Reutemann","Ferrari",87),("Gilles Villeneuve","Ferrari",90),("Mario Andretti","Lotus",93),("Gunnar Nilsson","Lotus",81),("Jody Scheckter","Wolf",90),("James Hunt","McLaren",88),("Jochen Mass","McLaren",80),("Patrick Depailler","Tyrrell",82),("Ronnie Peterson","Tyrrell",84),("Jacques Laffite","Ligier",83),("Alan Jones","Shadow",84),("Riccardo Patrese","Shadow",82),("Vittorio Brambilla","Surtees",76),("John Watson","Brabham",84),("Hans-Joachim Stuck","Brabham",76),("Emerson Fittipaldi","Copersucar",84),("Clay Regazzoni","Ensign",78),("Jean-Pierre Jarier","ATS",76),("Patrick Tambay","Ensign",78))},
    1978: {"champion": "Mario Andretti", "champion_team": "Lotus", "constructors_champion": "Lotus", "num_races": 16,
        "drivers": _D(("Mario Andretti","Lotus",96),("Ronnie Peterson","Lotus",92),("Carlos Reutemann","Ferrari",89),("Gilles Villeneuve","Ferrari",89),("Niki Lauda","Brabham",90),("John Watson","Brabham",84),("Jody Scheckter","Wolf",85),("Bobby Rahal","Wolf",76),("Patrick Depailler","Tyrrell",83),("Didier Pironi","Tyrrell",84),("Jacques Laffite","Ligier",83),("Jean-Pierre Jabouille","Renault",82),("Rene Arnoux","Renault",80),("Riccardo Patrese","Arrows",82),("Rolf Stommelen","Arrows",74),("James Hunt","McLaren",84),("Patrick Tambay","McLaren",80),("Emerson Fittipaldi","Copersucar",82),("Alan Jones","Williams",84),("Hans-Joachim Stuck","Shadow",74))},
    1979: {"champion": "Jody Scheckter", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 15,
        "drivers": _D(("Jody Scheckter","Ferrari",92),("Gilles Villeneuve","Ferrari",93),("Alan Jones","Williams",91),("Clay Regazzoni","Williams",82),("Jacques Laffite","Ligier",85),("Patrick Depailler","Ligier",83),("Carlos Reutemann","Lotus",85),("Mario Andretti","Lotus",86),("Rene Arnoux","Renault",83),("Jean-Pierre Jabouille","Renault",82),("Niki Lauda","Brabham",88),("Nelson Piquet","Brabham",86),("Jody Scheckter","Ferrari",92),("John Watson","McLaren",82),("Patrick Tambay","McLaren",80),("Didier Pironi","Tyrrell",83),("Jean-Pierre Jarier","Tyrrell",78),("Elio de Angelis","Shadow",82),("Jan Lammers","Shadow",70),("Riccardo Patrese","Arrows",82))},
    1980: {"champion": "Alan Jones", "champion_team": "Williams", "constructors_champion": "Williams", "num_races": 14,
        "drivers": _D(("Alan Jones","Williams",94),("Carlos Reutemann","Williams",88),("Nelson Piquet","Brabham",92),("Ricardo Zunino","Brabham",72),("Jacques Laffite","Ligier",85),("Didier Pironi","Ligier",84),("Rene Arnoux","Renault",84),("Jean-Pierre Jabouille","Renault",82),("Gilles Villeneuve","Ferrari",90),("Jody Scheckter","Ferrari",84),("Elio de Angelis","Lotus",81),("Mario Andretti","Lotus",84),("John Watson","McLaren",80),("Alain Prost","McLaren",90),("Keke Rosberg","Fittipaldi",83),("Emerson Fittipaldi","Fittipaldi",82),("Riccardo Patrese","Arrows",82),("Jochen Mass","Arrows",76),("Bruno Giacomelli","Alfa Romeo",82),("Patrick Depailler","Alfa Romeo",82))},
    1981: {"champion": "Nelson Piquet", "champion_team": "Brabham", "constructors_champion": "Williams", "num_races": 15,
        "drivers": _D(("Nelson Piquet","Brabham",94),("Hector Rebaque","Brabham",74),("Carlos Reutemann","Williams",92),("Alan Jones","Williams",89),("Jacques Laffite","Ligier",86),("Jean-Pierre Jabouille","Ligier",78),("Alain Prost","Renault",90),("Rene Arnoux","Renault",83),("Gilles Villeneuve","Ferrari",89),("Didier Pironi","Ferrari",84),("Elio de Angelis","Lotus",82),("Nigel Mansell","Lotus",81),("John Watson","McLaren",85),("Andrea de Cesaris","McLaren",80),("Riccardo Patrese","Arrows",82),("Siegfried Stohr","Arrows",70),("Bruno Giacomelli","Alfa Romeo",82),("Mario Andretti","Alfa Romeo",82),("Keke Rosberg","Fittipaldi",84),("Chico Serra","Fittipaldi",70))},
    1982: {"champion": "Keke Rosberg", "champion_team": "Williams", "constructors_champion": "Ferrari", "num_races": 16,
        "drivers": _D(("Keke Rosberg","Williams",90),("Carlos Reutemann","Williams",84),("Derek Daly","Williams",78),("Mario Andretti","Ferrari",84),("Didier Pironi","Ferrari",89),("Gilles Villeneuve","Ferrari",90),("Patrick Tambay","Ferrari",85),("Alain Prost","Renault",92),("Rene Arnoux","Renault",84),("John Watson","McLaren",86),("Niki Lauda","McLaren",89),("Nelson Piquet","Brabham",90),("Riccardo Patrese","Brabham",82),("Elio de Angelis","Lotus",83),("Nigel Mansell","Lotus",83),("Michele Alboreto","Tyrrell",83),("Brian Henton","Tyrrell",70),("Jacques Laffite","Ligier",84),("Eddie Cheever","Ligier",82),("Andrea de Cesaris","Alfa Romeo",80))},
    1983: {"champion": "Nelson Piquet", "champion_team": "Brabham", "constructors_champion": "Ferrari", "num_races": 15,
        "drivers": _D(("Nelson Piquet","Brabham",94),("Riccardo Patrese","Brabham",84),("Alain Prost","Renault",93),("Eddie Cheever","Renault",82),("Rene Arnoux","Ferrari",87),("Patrick Tambay","Ferrari",86),("Keke Rosberg","Williams",86),("Jacques Laffite","Williams",82),("John Watson","McLaren",83),("Niki Lauda","McLaren",89),("Elio de Angelis","Lotus",83),("Nigel Mansell","Lotus",84),("Michele Alboreto","Tyrrell",83),("Danny Sullivan","Tyrrell",76),("Andrea de Cesaris","Alfa Romeo",80),("Mauro Baldi","Alfa Romeo",76),("Marc Surer","Arrows",78),("Chico Serra","Arrows",70),("Derek Warwick","Toleman",80),("Bruno Giacomelli","Toleman",78))},
    1984: {"champion": "Niki Lauda", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 16,
        "drivers": _D(("Niki Lauda","McLaren",93),("Alain Prost","McLaren",96),("Elio de Angelis","Lotus",85),("Nigel Mansell","Lotus",85),("Michele Alboreto","Ferrari",86),("Rene Arnoux","Ferrari",84),("Derek Warwick","Renault",83),("Patrick Tambay","Renault",83),("Nelson Piquet","Brabham",90),("Teo Fabi","Brabham",78),("Keke Rosberg","Williams",87),("Jacques Laffite","Williams",82),("Ayrton Senna","Toleman",90),("Johnny Cecotto","Toleman",74),("Andrea de Cesaris","Ligier",80),("Francois Hesnault","Ligier",70),("Riccardo Patrese","Alfa Romeo",80),("Eddie Cheever","Alfa Romeo",80),("Stefan Bellof","Tyrrell",82),("Martin Brundle","Tyrrell",82))},
    1985: {"champion": "Alain Prost", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 16,
        "drivers": _D(("Alain Prost","McLaren",97),("Niki Lauda","McLaren",89),("John Watson","McLaren",80),("Michele Alboreto","Ferrari",89),("Stefan Johansson","Ferrari",83),("Rene Arnoux","Ferrari",82),("Ayrton Senna","Lotus",93),("Elio de Angelis","Lotus",85),("Nigel Mansell","Williams",88),("Keke Rosberg","Williams",88),("Nelson Piquet","Brabham",89),("Marc Surer","Brabham",78),("Derek Warwick","Renault",82),("Patrick Tambay","Renault",82),("Andrea de Cesaris","Ligier",78),("Jacques Laffite","Ligier",82),("Riccardo Patrese","Alfa Romeo",80),("Eddie Cheever","Alfa Romeo",80),("Thierry Boutsen","Arrows",82),("Gerhard Berger","Arrows",83))},
    1986: {"champion": "Alain Prost", "champion_team": "McLaren", "constructors_champion": "Williams", "num_races": 16,
        "drivers": _D(("Alain Prost","McLaren",96),("Keke Rosberg","McLaren",87),("Nigel Mansell","Williams",93),("Nelson Piquet","Williams",92),("Ayrton Senna","Lotus",94),("Johnny Dumfries","Lotus",76),("Michele Alboreto","Ferrari",84),("Stefan Johansson","Ferrari",83),("Gerhard Berger","Benetton",83),("Teo Fabi","Benetton",78),("Rene Arnoux","Ligier",81),("Jacques Laffite","Ligier",80),("Riccardo Patrese","Brabham",82),("Elio de Angelis","Brabham",83),("Derek Warwick","Brabham",80),("Martin Brundle","Tyrrell",82),("Philippe Streiff","Tyrrell",78),("Thierry Boutsen","Arrows",82),("Christian Danner","Arrows",74),("Andrea de Cesaris","Minardi",76))},
    1987: {"champion": "Nelson Piquet", "champion_team": "Williams", "constructors_champion": "Williams", "num_races": 16,
        "drivers": _D(("Nelson Piquet","Williams",94),("Nigel Mansell","Williams",93),("Ayrton Senna","Lotus",95),("Satoru Nakajima","Lotus",76),("Alain Prost","McLaren",95),("Stefan Johansson","McLaren",83),("Gerhard Berger","Ferrari",87),("Michele Alboreto","Ferrari",84),("Thierry Boutsen","Benetton",82),("Teo Fabi","Benetton",80),("Riccardo Patrese","Brabham",82),("Andrea de Cesaris","Brabham",78),("Eddie Cheever","Arrows",80),("Derek Warwick","Arrows",80),("Rene Arnoux","Ligier",78),("Piercarlo Ghinzani","Ligier",70),("Ivan Capelli","March",82),("Adrian Campos","Minardi",70),("Alessandro Nannini","Minardi",82),("Martin Brundle","Zakspeed",80))},
    1988: {"champion": "Ayrton Senna", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 16,
        "drivers": _D(("Ayrton Senna","McLaren",98),("Alain Prost","McLaren",97),("Gerhard Berger","Ferrari",88),("Michele Alboreto","Ferrari",84),("Thierry Boutsen","Benetton",85),("Alessandro Nannini","Benetton",83),("Nelson Piquet","Lotus",89),("Satoru Nakajima","Lotus",76),("Nigel Mansell","Williams",90),("Riccardo Patrese","Williams",84),("Ivan Capelli","March",82),("Mauricio Gugelmin","March",78),("Derek Warwick","Arrows",81),("Eddie Cheever","Arrows",80),("Rene Arnoux","Ligier",78),("Stefan Johansson","Ligier",80),("Andrea de Cesaris","Rial",78),("Jonathan Palmer","Tyrrell",80),("Julian Bailey","Tyrrell",70),("Philippe Alliot","Larrousse",78))},
    1989: {"champion": "Alain Prost", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 16,
        "drivers": _D(("Alain Prost","McLaren",96),("Ayrton Senna","McLaren",98),("Nigel Mansell","Ferrari",92),("Gerhard Berger","Ferrari",87),("Riccardo Patrese","Williams",86),("Thierry Boutsen","Williams",85),("Nelson Piquet","Lotus",87),("Satoru Nakajima","Lotus",76),("Alessandro Nannini","Benetton",85),("Emanuele Pirro","Benetton",78),("Jean Alesi","Tyrrell",84),("Michele Alboreto","Tyrrell",82),("Jonathan Palmer","Tyrrell",78),("Ivan Capelli","March",82),("Mauricio Gugelmin","March",78),("Derek Warwick","Arrows",80),("Eddie Cheever","Arrows",80),("Andrea de Cesaris","Dallara",78),("Alex Caffi","Dallara",78),("Martin Brundle","Brabham",80))},
    1990: {"champion": "Ayrton Senna", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 16,
        "drivers": _D(("Ayrton Senna","McLaren",98),("Gerhard Berger","McLaren",88),("Alain Prost","Ferrari",96),("Nigel Mansell","Ferrari",92),("Riccardo Patrese","Williams",86),("Thierry Boutsen","Williams",84),("Nelson Piquet","Benetton",89),("Alessandro Nannini","Benetton",84),("Roberto Moreno","Benetton",78),("Jean Alesi","Tyrrell",85),("Satoru Nakajima","Tyrrell",76),("Ivan Capelli","Leyton House",82),("Mauricio Gugelmin","Leyton House",78),("Aguri Suzuki","Larrousse",78),("Eric Bernard","Larrousse",76),("Andrea de Cesaris","Dallara",78),("Emanuele Pirro","Dallara",78),("Derek Warwick","Lotus",80),("Martin Donnelly","Lotus",78),("Stefano Modena","Brabham",80))},
    1991: {"champion": "Ayrton Senna", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 16,
        "drivers": _D(("Ayrton Senna","McLaren",99),("Gerhard Berger","McLaren",88),("Nigel Mansell","Williams",93),("Riccardo Patrese","Williams",87),("Alain Prost","Ferrari",93),("Jean Alesi","Ferrari",86),("Michael Schumacher","Benetton",92),("Nelson Piquet","Benetton",87),("Roberto Moreno","Benetton",78),("Stefano Modena","Tyrrell",81),("Satoru Nakajima","Tyrrell",76),("Ivan Capelli","Leyton House",80),("Karl Wendlinger","Leyton House",78),("Andrea de Cesaris","Jordan",78),("Bertrand Gachot","Jordan",76),("Aguri Suzuki","Larrousse",76),("Eric Bernard","Larrousse",76),("Mika Hakkinen","Lotus",84),("Julian Bailey","Lotus",70),("Emanuele Pirro","Dallara",78))},
    1992: {"champion": "Nigel Mansell", "champion_team": "Williams", "constructors_champion": "Williams", "num_races": 16,
        "drivers": _D(("Nigel Mansell","Williams",97),("Riccardo Patrese","Williams",88),("Michael Schumacher","Benetton",94),("Martin Brundle","Benetton",84),("Ayrton Senna","McLaren",96),("Gerhard Berger","McLaren",87),("Jean Alesi","Ferrari",85),("Ivan Capelli","Ferrari",80),("Andrea de Cesaris","Tyrrell",78),("Olivier Grouillard","Tyrrell",74),("Mika Hakkinen","Lotus",84),("Johnny Herbert","Lotus",82),("Michele Alboreto","Footwork",78),("Aguri Suzuki","Footwork",76),("Karl Wendlinger","March",78),("Paul Belmondo","March",70),("Erik Comas","Ligier",78),("Thierry Boutsen","Ligier",80),("Pierluigi Martini","Dallara",78),("JJ Lehto","Dallara",76))},
    1993: {"champion": "Alain Prost", "champion_team": "Williams", "constructors_champion": "Williams", "num_races": 16,
        "drivers": _D(("Alain Prost","Williams",96),("Damon Hill","Williams",89),("Ayrton Senna","McLaren",97),("Michael Andretti","McLaren",78),("Mika Hakkinen","McLaren",86),("Michael Schumacher","Benetton",94),("Riccardo Patrese","Benetton",85),("Jean Alesi","Ferrari",84),("Gerhard Berger","Ferrari",86),("Rubens Barrichello","Jordan",84),("Thierry Boutsen","Jordan",78),("Emanuele Naspetti","Jordan",70),("Martin Brundle","Ligier",82),("Mark Blundell","Ligier",78),("Karl Wendlinger","Sauber",80),("JJ Lehto","Sauber",78),("Johnny Herbert","Lotus",82),("Alessandro Zanardi","Lotus",78),("Christian Fittipaldi","Minardi",76),("Ukyo Katayama","Tyrrell",76))},
    1994: {"champion": "Michael Schumacher", "champion_team": "Benetton", "constructors_champion": "Williams", "num_races": 16,
        "drivers": _D(("Michael Schumacher","Benetton",97),("Jos Verstappen","Benetton",82),("JJ Lehto","Benetton",78),("Damon Hill","Williams",91),("David Coulthard","Williams",84),("Nigel Mansell","Williams",90),("Ayrton Senna","Williams",99),("Gerhard Berger","Ferrari",86),("Jean Alesi","Ferrari",84),("Nicola Larini","Ferrari",76),("Mika Hakkinen","McLaren",87),("Martin Brundle","McLaren",82),("Rubens Barrichello","Jordan",84),("Eddie Irvine","Jordan",82),("Ukyo Katayama","Tyrrell",78),("Mark Blundell","Tyrrell",78),("Heinz-Harald Frentzen","Sauber",84),("Karl Wendlinger","Sauber",78),("Olivier Panis","Ligier",80),("Eric Bernard","Ligier",76))},
    1995: {"champion": "Michael Schumacher", "champion_team": "Benetton", "constructors_champion": "Benetton", "num_races": 17,
        "drivers": _D(("Michael Schumacher","Benetton",98),("Johnny Herbert","Benetton",84),("Damon Hill","Williams",90),("David Coulthard","Williams",87),("Jean Alesi","Ferrari",85),("Gerhard Berger","Ferrari",85),("Mika Hakkinen","McLaren",88),("Mark Blundell","McLaren",78),("Nigel Mansell","McLaren",88),("Rubens Barrichello","Jordan",82),("Eddie Irvine","Jordan",82),("Olivier Panis","Ligier",82),("Martin Brundle","Ligier",81),("Aguri Suzuki","Ligier",76),("Heinz-Harald Frentzen","Sauber",83),("Karl Wendlinger","Sauber",76),("Jean-Christophe Boullion","Sauber",74),("Ukyo Katayama","Tyrrell",78),("Mika Salo","Tyrrell",80),("Pedro Lamy","Minardi",76))},
    1996: {"champion": "Damon Hill", "champion_team": "Williams", "constructors_champion": "Williams", "num_races": 16,
        "drivers": _D(("Damon Hill","Williams",93),("Jacques Villeneuve","Williams",90),("Michael Schumacher","Ferrari",97),("Eddie Irvine","Ferrari",82),("Mika Hakkinen","McLaren",87),("David Coulthard","McLaren",85),("Jean Alesi","Benetton",85),("Gerhard Berger","Benetton",84),("Rubens Barrichello","Jordan",82),("Martin Brundle","Jordan",80),("Olivier Panis","Ligier",81),("Pedro Diniz","Ligier",74),("Heinz-Harald Frentzen","Sauber",83),("Johnny Herbert","Sauber",82),("Mika Salo","Tyrrell",80),("Ukyo Katayama","Tyrrell",76),("Jos Verstappen","Footwork",80),("Ricardo Rosset","Footwork",70),("Pedro Lamy","Minardi",76),("Giancarlo Fisichella","Minardi",82))},
    1997: {"champion": "Jacques Villeneuve", "champion_team": "Williams", "constructors_champion": "Williams", "num_races": 17,
        "drivers": _D(("Jacques Villeneuve","Williams",93),("Heinz-Harald Frentzen","Williams",85),("Michael Schumacher","Ferrari",96),("Eddie Irvine","Ferrari",83),("Mika Hakkinen","McLaren",89),("David Coulthard","McLaren",86),("Jean Alesi","Benetton",83),("Gerhard Berger","Benetton",83),("Giancarlo Fisichella","Jordan",84),("Ralf Schumacher","Jordan",82),("Olivier Panis","Prost",84),("Shinji Nakano","Prost",76),("Johnny Herbert","Sauber",82),("Nicola Larini","Sauber",76),("Rubens Barrichello","Stewart",84),("Jan Magnussen","Stewart",78),("Damon Hill","Arrows",86),("Pedro Diniz","Arrows",74),("Mika Salo","Tyrrell",80),("Jos Verstappen","Tyrrell",78))},
    1998: {"champion": "Mika Hakkinen", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 16,
        "drivers": _D(("Mika Hakkinen","McLaren",95),("David Coulthard","McLaren",87),("Michael Schumacher","Ferrari",97),("Eddie Irvine","Ferrari",84),("Jacques Villeneuve","Williams",86),("Heinz-Harald Frentzen","Williams",83),("Damon Hill","Jordan",85),("Ralf Schumacher","Jordan",82),("Alexander Wurz","Benetton",81),("Giancarlo Fisichella","Benetton",83),("Rubens Barrichello","Stewart",83),("Jan Magnussen","Stewart",76),("Jos Verstappen","Stewart",78),("Jean Alesi","Sauber",83),("Johnny Herbert","Sauber",82),("Olivier Panis","Prost",83),("Jarno Trulli","Prost",82),("Mika Salo","Arrows",80),("Pedro Diniz","Arrows",74),("Ricardo Rosset","Tyrrell",68))},
    1999: {"champion": "Mika Hakkinen", "champion_team": "McLaren", "constructors_champion": "Ferrari", "num_races": 16,
        "drivers": _D(("Mika Hakkinen","McLaren",95),("David Coulthard","McLaren",87),("Michael Schumacher","Ferrari",97),("Eddie Irvine","Ferrari",88),("Mika Salo","Ferrari",80),("Heinz-Harald Frentzen","Jordan",86),("Damon Hill","Jordan",84),("Ralf Schumacher","Williams",83),("Alessandro Zanardi","Williams",78),("Rubens Barrichello","Stewart",84),("Johnny Herbert","Stewart",81),("Giancarlo Fisichella","Benetton",82),("Alexander Wurz","Benetton",80),("Jean Alesi","Sauber",82),("Pedro Diniz","Sauber",74),("Olivier Panis","Prost",82),("Jarno Trulli","Prost",81),("Pedro de la Rosa","Arrows",78),("Toranosuke Takagi","Arrows",70),("Marc Gene","Minardi",76))},
    2000: {"champion": "Michael Schumacher", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 17,
        "drivers": _D(("Michael Schumacher","Ferrari",97),("Rubens Barrichello","Ferrari",88),("Mika Hakkinen","McLaren",95),("David Coulthard","McLaren",89),("Ralf Schumacher","Williams",85),("Jenson Button","Williams",83),("Giancarlo Fisichella","Benetton",83),("Alexander Wurz","Benetton",80),("Jacques Villeneuve","BAR",83),("Ricardo Zonta","BAR",76),("Heinz-Harald Frentzen","Jordan",83),("Jarno Trulli","Jordan",82),("Jean Alesi","Prost",82),("Nick Heidfeld","Prost",80),("Eddie Irvine","Jaguar",84),("Johnny Herbert","Jaguar",80),("Mika Salo","Sauber",80),("Pedro Diniz","Sauber",72),("Pedro de la Rosa","Arrows",77),("Jos Verstappen","Arrows",78))},
    2001: {"champion": "Michael Schumacher", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 17,
        "drivers": _D(("Michael Schumacher","Ferrari",98),("Rubens Barrichello","Ferrari",87),("David Coulthard","McLaren",89),("Mika Hakkinen","McLaren",93),("Ralf Schumacher","Williams",86),("Juan Pablo Montoya","Williams",88),("Jarno Trulli","Jordan",82),("Heinz-Harald Frentzen","Jordan",83),("Jacques Villeneuve","BAR",82),("Olivier Panis","BAR",81),("Nick Heidfeld","Sauber",82),("Kimi Raikkonen","Sauber",85),("Giancarlo Fisichella","Benetton",83),("Jenson Button","Benetton",83),("Jean Alesi","Prost",82),("Luciano Burti","Prost",72),("Eddie Irvine","Jaguar",82),("Pedro de la Rosa","Jaguar",76),("Jos Verstappen","Arrows",78),("Enrique Bernoldi","Arrows",70))},
    2002: {"champion": "Michael Schumacher", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 17,
        "drivers": _D(("Michael Schumacher","Ferrari",99),("Rubens Barrichello","Ferrari",90),("Juan Pablo Montoya","Williams",89),("Ralf Schumacher","Williams",86),("David Coulthard","McLaren",87),("Kimi Raikkonen","McLaren",89),("Jenson Button","Renault",83),("Jarno Trulli","Renault",82),("Nick Heidfeld","Sauber",81),("Felipe Massa","Sauber",78),("Heinz-Harald Frentzen","Arrows",82),("Enrique Bernoldi","Arrows",72),("Giancarlo Fisichella","Jordan",83),("Takuma Sato","Jordan",76),("Jacques Villeneuve","BAR",82),("Olivier Panis","BAR",80),("Eddie Irvine","Jaguar",80),("Pedro de la Rosa","Jaguar",76),("Mark Webber","Minardi",84),("Alex Yoong","Minardi",68))},
    2003: {"champion": "Michael Schumacher", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 16,
        "drivers": _D(("Michael Schumacher","Ferrari",97),("Rubens Barrichello","Ferrari",88),("Kimi Raikkonen","McLaren",93),("David Coulthard","McLaren",86),("Juan Pablo Montoya","Williams",90),("Ralf Schumacher","Williams",86),("Fernando Alonso","Renault",90),("Jarno Trulli","Renault",84),("Jenson Button","BAR",83),("Jacques Villeneuve","BAR",81),("Mark Webber","Jaguar",83),("Antonio Pizzonia","Jaguar",74),("Nick Heidfeld","Sauber",81),("Heinz-Harald Frentzen","Sauber",80),("Giancarlo Fisichella","Jordan",83),("Ralph Firman","Jordan",70),("Cristiano da Matta","Toyota",80),("Olivier Panis","Toyota",78),("Justin Wilson","Minardi",76),("Jos Verstappen","Minardi",76))},
    2004: {"champion": "Michael Schumacher", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 18,
        "drivers": _D(("Michael Schumacher","Ferrari",99),("Rubens Barrichello","Ferrari",89),("Jenson Button","BAR",86),("Takuma Sato","BAR",82),("Fernando Alonso","Renault",90),("Jarno Trulli","Renault",83),("Jacques Villeneuve","Renault",80),("Juan Pablo Montoya","Williams",87),("Ralf Schumacher","Williams",84),("Antonio Pizzonia","Williams",74),("Marc Gene","Williams",74),("Kimi Raikkonen","McLaren",91),("David Coulthard","McLaren",84),("Giancarlo Fisichella","Sauber",83),("Felipe Massa","Sauber",80),("Mark Webber","Jaguar",84),("Christian Klien","Jaguar",76),("Cristiano da Matta","Toyota",80),("Olivier Panis","Toyota",78),("Nick Heidfeld","Jordan",81))},
    2005: {"champion": "Fernando Alonso", "champion_team": "Renault", "constructors_champion": "Renault", "num_races": 19,
        "drivers": _D(("Fernando Alonso","Renault",96),("Giancarlo Fisichella","Renault",84),("Kimi Raikkonen","McLaren",94),("Juan Pablo Montoya","McLaren",88),("Michael Schumacher","Ferrari",94),("Rubens Barrichello","Ferrari",84),("Jarno Trulli","Toyota",83),("Ralf Schumacher","Toyota",84),("Jenson Button","BAR",84),("Takuma Sato","BAR",80),("Mark Webber","Williams",82),("Nick Heidfeld","Williams",83),("Antonio Pizzonia","Williams",74),("David Coulthard","Red Bull",84),("Christian Klien","Red Bull",76),("Vitantonio Liuzzi","Red Bull",76),("Felipe Massa","Sauber",83),("Jacques Villeneuve","Sauber",80),("Tiago Monteiro","Jordan",70),("Narain Karthikeyan","Jordan",70))},
    2006: {"champion": "Fernando Alonso", "champion_team": "Renault", "constructors_champion": "Renault", "num_races": 18,
        "drivers": _D(("Fernando Alonso","Renault",97),("Giancarlo Fisichella","Renault",84),("Michael Schumacher","Ferrari",96),("Felipe Massa","Ferrari",87),("Kimi Raikkonen","McLaren",92),("Juan Pablo Montoya","McLaren",85),("Pedro de la Rosa","McLaren",78),("Jenson Button","Honda",86),("Rubens Barrichello","Honda",83),("Nick Heidfeld","BMW Sauber",83),("Jacques Villeneuve","BMW Sauber",78),("Robert Kubica","BMW Sauber",85),("Ralf Schumacher","Toyota",82),("Jarno Trulli","Toyota",82),("Mark Webber","Williams",83),("Nico Rosberg","Williams",82),("David Coulthard","Red Bull",82),("Christian Klien","Red Bull",76),("Vitantonio Liuzzi","Toro Rosso",76),("Scott Speed","Toro Rosso",74))},
    2007: {"champion": "Kimi Raikkonen", "champion_team": "Ferrari", "constructors_champion": "Ferrari", "num_races": 17,
        "drivers": _D(("Kimi Raikkonen","Ferrari",95),("Felipe Massa","Ferrari",88),("Lewis Hamilton","McLaren",93),("Fernando Alonso","McLaren",95),("Nick Heidfeld","BMW Sauber",84),("Robert Kubica","BMW Sauber",85),("Heikki Kovalainen","Renault",83),("Giancarlo Fisichella","Renault",82),("Nico Rosberg","Williams",83),("Alexander Wurz","Williams",78),("David Coulthard","Red Bull",81),("Mark Webber","Red Bull",83),("Jarno Trulli","Toyota",82),("Ralf Schumacher","Toyota",80),("Rubens Barrichello","Honda",81),("Jenson Button","Honda",83),("Vitantonio Liuzzi","Toro Rosso",76),("Sebastian Vettel","Toro Rosso",86),("Anthony Davidson","Super Aguri",78),("Takuma Sato","Super Aguri",78))},
    2008: {"champion": "Lewis Hamilton", "champion_team": "McLaren", "constructors_champion": "Ferrari", "num_races": 18,
        "drivers": _D(("Lewis Hamilton","McLaren",95),("Heikki Kovalainen","McLaren",84),("Felipe Massa","Ferrari",94),("Kimi Raikkonen","Ferrari",92),("Robert Kubica","BMW Sauber",88),("Nick Heidfeld","BMW Sauber",84),("Fernando Alonso","Renault",93),("Nelson Piquet Jr","Renault",76),("Jarno Trulli","Toyota",82),("Timo Glock","Toyota",81),("Sebastian Vettel","Toro Rosso",88),("Sebastien Bourdais","Toro Rosso",78),("Mark Webber","Red Bull",83),("David Coulthard","Red Bull",80),("Nico Rosberg","Williams",83),("Kazuki Nakajima","Williams",76),("Rubens Barrichello","Honda",82),("Jenson Button","Honda",84),("Giancarlo Fisichella","Force India",80),("Adrian Sutil","Force India",78))},
    2009: {"champion": "Jenson Button", "champion_team": "Brawn", "constructors_champion": "Brawn", "num_races": 17,
        "drivers": _D(("Jenson Button","Brawn",92),("Rubens Barrichello","Brawn",87),("Sebastian Vettel","Red Bull",93),("Mark Webber","Red Bull",87),("Lewis Hamilton","McLaren",94),("Heikki Kovalainen","McLaren",82),("Kimi Raikkonen","Ferrari",90),("Felipe Massa","Ferrari",90),("Luca Badoer","Ferrari",70),("Giancarlo Fisichella","Ferrari",80),("Nico Rosberg","Williams",85),("Kazuki Nakajima","Williams",76),("Fernando Alonso","Renault",92),("Nelson Piquet Jr","Renault",76),("Romain Grosjean","Renault",78),("Jarno Trulli","Toyota",83),("Timo Glock","Toyota",82),("Robert Kubica","BMW Sauber",88),("Nick Heidfeld","BMW Sauber",83),("Adrian Sutil","Force India",80))},
    2010: {"champion": "Sebastian Vettel", "champion_team": "Red Bull", "constructors_champion": "Red Bull", "num_races": 19,
        "drivers": _D(("Sebastian Vettel","Red Bull",96),("Mark Webber","Red Bull",89),("Fernando Alonso","Ferrari",95),("Felipe Massa","Ferrari",86),("Lewis Hamilton","McLaren",94),("Jenson Button","McLaren",89),("Nico Rosberg","Mercedes",86),("Michael Schumacher","Mercedes",89),("Robert Kubica","Renault",88),("Vitaly Petrov","Renault",78),("Rubens Barrichello","Williams",83),("Nico Hulkenberg","Williams",82),("Adrian Sutil","Force India",82),("Vitantonio Liuzzi","Force India",78),("Kamui Kobayashi","Sauber",82),("Pedro de la Rosa","Sauber",76),("Sebastien Buemi","Toro Rosso",78),("Jaime Alguersuari","Toro Rosso",77),("Heikki Kovalainen","Lotus",76),("Jarno Trulli","Lotus",76))},
    2011: {"champion": "Sebastian Vettel", "champion_team": "Red Bull", "constructors_champion": "Red Bull", "num_races": 19,
        "drivers": _D(("Sebastian Vettel","Red Bull",99),("Mark Webber","Red Bull",88),("Jenson Button","McLaren",90),("Lewis Hamilton","McLaren",93),("Fernando Alonso","Ferrari",95),("Felipe Massa","Ferrari",85),("Nico Rosberg","Mercedes",87),("Michael Schumacher","Mercedes",87),("Vitaly Petrov","Renault",78),("Nick Heidfeld","Renault",81),("Adrian Sutil","Force India",83),("Paul di Resta","Force India",81),("Kamui Kobayashi","Sauber",83),("Sergio Perez","Sauber",84),("Rubens Barrichello","Williams",82),("Pastor Maldonado","Williams",78),("Jaime Alguersuari","Toro Rosso",77),("Sebastien Buemi","Toro Rosso",77),("Heikki Kovalainen","Lotus",76),("Jarno Trulli","Lotus",75))},
    2012: {"champion": "Sebastian Vettel", "champion_team": "Red Bull", "constructors_champion": "Red Bull", "num_races": 20,
        "drivers": _D(("Sebastian Vettel","Red Bull",97),("Mark Webber","Red Bull",88),("Lewis Hamilton","McLaren",94),("Jenson Button","McLaren",89),("Fernando Alonso","Ferrari",96),("Felipe Massa","Ferrari",85),("Michael Schumacher","Mercedes",86),("Nico Rosberg","Mercedes",87),("Kimi Raikkonen","Lotus",91),("Romain Grosjean","Lotus",85),("Sergio Perez","Sauber",85),("Kamui Kobayashi","Sauber",82),("Nico Hulkenberg","Force India",85),("Paul di Resta","Force India",81),("Pastor Maldonado","Williams",80),("Bruno Senna","Williams",78),("Daniel Ricciardo","Toro Rosso",81),("Jean-Eric Vergne","Toro Rosso",79),("Heikki Kovalainen","Caterham",75),("Vitaly Petrov","Caterham",74))},
    2013: {"champion": "Sebastian Vettel", "champion_team": "Red Bull", "constructors_champion": "Red Bull", "num_races": 19,
        "drivers": _D(("Sebastian Vettel","Red Bull",99),("Mark Webber","Red Bull",88),("Nico Rosberg","Mercedes",88),("Lewis Hamilton","Mercedes",95),("Fernando Alonso","Ferrari",95),("Felipe Massa","Ferrari",84),("Kimi Raikkonen","Lotus",90),("Romain Grosjean","Lotus",86),("Jenson Button","McLaren",87),("Sergio Perez","McLaren",84),("Adrian Sutil","Force India",82),("Paul di Resta","Force India",82),("Nico Hulkenberg","Sauber",85),("Esteban Gutierrez","Sauber",77),("Daniel Ricciardo","Toro Rosso",85),("Jean-Eric Vergne","Toro Rosso",79),("Valtteri Bottas","Williams",84),("Pastor Maldonado","Williams",78),("Giedo van der Garde","Caterham",73),("Charles Pic","Caterham",73))},
    2014: {"champion": "Lewis Hamilton", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 19,
        "drivers": _D(("Lewis Hamilton","Mercedes",97),("Nico Rosberg","Mercedes",93),("Daniel Ricciardo","Red Bull",90),("Sebastian Vettel","Red Bull",92),("Valtteri Bottas","Williams",86),("Felipe Massa","Williams",85),("Fernando Alonso","Ferrari",92),("Kimi Raikkonen","Ferrari",87),("Jenson Button","McLaren",84),("Kevin Magnussen","McLaren",82),("Nico Hulkenberg","Force India",85),("Sergio Perez","Force India",84),("Jean-Eric Vergne","Toro Rosso",78),("Daniil Kvyat","Toro Rosso",81),("Romain Grosjean","Lotus",83),("Pastor Maldonado","Lotus",76),("Esteban Gutierrez","Sauber",76),("Adrian Sutil","Sauber",79),("Jules Bianchi","Marussia",78),("Max Chilton","Marussia",72))},
    2015: {"champion": "Lewis Hamilton", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 19,
        "drivers": _D(("Lewis Hamilton","Mercedes",98),("Nico Rosberg","Mercedes",92),("Sebastian Vettel","Ferrari",94),("Kimi Raikkonen","Ferrari",89),("Valtteri Bottas","Williams",87),("Felipe Massa","Williams",85),("Daniel Ricciardo","Red Bull",89),("Daniil Kvyat","Red Bull",83),("Sergio Perez","Force India",84),("Nico Hulkenberg","Force India",85),("Romain Grosjean","Lotus",84),("Pastor Maldonado","Lotus",76),("Max Verstappen","Toro Rosso",88),("Carlos Sainz","Toro Rosso",84),("Marcus Ericsson","Sauber",75),("Felipe Nasr","Sauber",78),("Fernando Alonso","McLaren",90),("Jenson Button","McLaren",84),("Roberto Merhi","Manor",70),("Will Stevens","Manor",70))},
    2016: {"champion": "Nico Rosberg", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 21,
        "drivers": _D(("Nico Rosberg","Mercedes",95),("Lewis Hamilton","Mercedes",97),("Daniel Ricciardo","Red Bull",90),("Max Verstappen","Red Bull",92),("Sebastian Vettel","Ferrari",93),("Kimi Raikkonen","Ferrari",89),("Sergio Perez","Force India",86),("Nico Hulkenberg","Force India",85),("Valtteri Bottas","Williams",86),("Felipe Massa","Williams",83),("Fernando Alonso","McLaren",89),("Jenson Button","McLaren",83),("Carlos Sainz","Toro Rosso",85),("Daniil Kvyat","Toro Rosso",80),("Romain Grosjean","Haas",84),("Esteban Gutierrez","Haas",76),("Kevin Magnussen","Renault",82),("Jolyon Palmer","Renault",74),("Marcus Ericsson","Sauber",75),("Felipe Nasr","Sauber",77))},
    2017: {"champion": "Lewis Hamilton", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 20,
        "drivers": _D(("Lewis Hamilton","Mercedes",97),("Valtteri Bottas","Mercedes",89),("Sebastian Vettel","Ferrari",95),("Kimi Raikkonen","Ferrari",88),("Max Verstappen","Red Bull",93),("Daniel Ricciardo","Red Bull",90),("Sergio Perez","Force India",85),("Esteban Ocon","Force India",84),("Felipe Massa","Williams",82),("Lance Stroll","Williams",76),("Fernando Alonso","McLaren",88),("Stoffel Vandoorne","McLaren",78),("Carlos Sainz","Toro Rosso",84),("Daniil Kvyat","Toro Rosso",78),("Nico Hulkenberg","Renault",85),("Jolyon Palmer","Renault",74),("Romain Grosjean","Haas",83),("Kevin Magnussen","Haas",82),("Marcus Ericsson","Sauber",75),("Pascal Wehrlein","Sauber",76))},
    2018: {"champion": "Lewis Hamilton", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 21,
        "drivers": _D(("Lewis Hamilton","Mercedes",98),("Valtteri Bottas","Mercedes",89),("Sebastian Vettel","Ferrari",94),("Kimi Raikkonen","Ferrari",88),("Max Verstappen","Red Bull",95),("Daniel Ricciardo","Red Bull",89),("Sergio Perez","Force India",85),("Esteban Ocon","Force India",83),("Romain Grosjean","Haas",83),("Kevin Magnussen","Haas",84),("Nico Hulkenberg","Renault",85),("Carlos Sainz","Renault",84),("Fernando Alonso","McLaren",88),("Stoffel Vandoorne","McLaren",77),("Pierre Gasly","Toro Rosso",84),("Brendon Hartley","Toro Rosso",75),("Charles Leclerc","Sauber",85),("Marcus Ericsson","Sauber",75),("Lance Stroll","Williams",76),("Sergey Sirotkin","Williams",72))},
    2019: {"champion": "Lewis Hamilton", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 21,
        "drivers": _D(("Lewis Hamilton","Mercedes",98),("Valtteri Bottas","Mercedes",90),("Max Verstappen","Red Bull",96),("Pierre Gasly","Red Bull",83),("Charles Leclerc","Ferrari",92),("Sebastian Vettel","Ferrari",92),("Carlos Sainz","McLaren",85),("Lando Norris","McLaren",86),("Daniel Ricciardo","Renault",87),("Nico Hulkenberg","Renault",84),("Daniil Kvyat","Toro Rosso",81),("Alexander Albon","Toro Rosso",83),("Sergio Perez","Racing Point",85),("Lance Stroll","Racing Point",78),("Kimi Raikkonen","Alfa Romeo",86),("Antonio Giovinazzi","Alfa Romeo",78),("Romain Grosjean","Haas",81),("Kevin Magnussen","Haas",82),("Robert Kubica","Williams",76),("George Russell","Williams",84))},
    2020: {"champion": "Lewis Hamilton", "champion_team": "Mercedes", "constructors_champion": "Mercedes", "num_races": 17,
        "drivers": _D(("Lewis Hamilton","Mercedes",99),("Valtteri Bottas","Mercedes",90),("Max Verstappen","Red Bull",96),("Alexander Albon","Red Bull",83),("Lando Norris","McLaren",87),("Carlos Sainz","McLaren",86),("Sergio Perez","Racing Point",86),("Lance Stroll","Racing Point",80),("Daniel Ricciardo","Renault",88),("Esteban Ocon","Renault",83),("Charles Leclerc","Ferrari",91),("Sebastian Vettel","Ferrari",84),("Pierre Gasly","AlphaTauri",86),("Daniil Kvyat","AlphaTauri",80),("Kimi Raikkonen","Alfa Romeo",84),("Antonio Giovinazzi","Alfa Romeo",78),("Romain Grosjean","Haas",78),("Kevin Magnussen","Haas",80),("George Russell","Williams",84),("Nicholas Latifi","Williams",72))},
    2021: {"champion": "Max Verstappen", "champion_team": "Red Bull", "constructors_champion": "Mercedes", "num_races": 22,
        "drivers": _D(("Max Verstappen","Red Bull",98),("Lewis Hamilton","Mercedes",97),("Valtteri Bottas","Mercedes",89),("Sergio Perez","Red Bull",87),("Lando Norris","McLaren",90),("Daniel Ricciardo","McLaren",85),("Carlos Sainz","Ferrari",88),("Charles Leclerc","Ferrari",90),("Fernando Alonso","Alpine",88),("Esteban Ocon","Alpine",85),("Pierre Gasly","AlphaTauri",87),("Yuki Tsunoda","AlphaTauri",79),("Sebastian Vettel","Aston Martin",85),("Lance Stroll","Aston Martin",79),("George Russell","Williams",85),("Nicholas Latifi","Williams",73),("Kimi Raikkonen","Alfa Romeo",82),("Antonio Giovinazzi","Alfa Romeo",77),("Mick Schumacher","Haas",76),("Nikita Mazepin","Haas",70))},
    2022: {"champion": "Max Verstappen", "champion_team": "Red Bull", "constructors_champion": "Red Bull", "num_races": 22,
        "drivers": _D(("Max Verstappen","Red Bull",99),("Sergio Perez","Red Bull",89),("Charles Leclerc","Ferrari",93),("Carlos Sainz","Ferrari",88),("George Russell","Mercedes",89),("Lewis Hamilton","Mercedes",92),("Lando Norris","McLaren",88),("Daniel Ricciardo","McLaren",82),("Esteban Ocon","Alpine",85),("Fernando Alonso","Alpine",87),("Pierre Gasly","AlphaTauri",86),("Yuki Tsunoda","AlphaTauri",80),("Sebastian Vettel","Aston Martin",84),("Lance Stroll","Aston Martin",79),("Kevin Magnussen","Haas",83),("Mick Schumacher","Haas",77),("Valtteri Bottas","Alfa Romeo",85),("Zhou Guanyu","Alfa Romeo",79),("Alexander Albon","Williams",82),("Nicholas Latifi","Williams",72))},
    2023: {"champion": "Max Verstappen", "champion_team": "Red Bull", "constructors_champion": "Red Bull", "num_races": 22,
        "drivers": _D(("Max Verstappen","Red Bull",99),("Sergio Perez","Red Bull",88),("Lewis Hamilton","Mercedes",92),("George Russell","Mercedes",88),("Fernando Alonso","Aston Martin",89),("Lance Stroll","Aston Martin",80),("Charles Leclerc","Ferrari",92),("Carlos Sainz","Ferrari",88),("Lando Norris","McLaren",91),("Oscar Piastri","McLaren",87),("Pierre Gasly","Alpine",85),("Esteban Ocon","Alpine",84),("Alexander Albon","Williams",84),("Logan Sargeant","Williams",70),("Valtteri Bottas","Alfa Romeo",83),("Zhou Guanyu","Alfa Romeo",78),("Yuki Tsunoda","AlphaTauri",81),("Daniel Ricciardo","AlphaTauri",82),("Kevin Magnussen","Haas",81),("Nico Hulkenberg","Haas",83))},
    2024: {"champion": "Max Verstappen", "champion_team": "Red Bull", "constructors_champion": "McLaren", "num_races": 24,
        "drivers": _D(("Max Verstappen","Red Bull",98),("Sergio Perez","Red Bull",83),("Lando Norris","McLaren",93),("Oscar Piastri","McLaren",91),("Charles Leclerc","Ferrari",93),("Carlos Sainz","Ferrari",90),("Lewis Hamilton","Mercedes",91),("George Russell","Mercedes",89),("Fernando Alonso","Aston Martin",88),("Lance Stroll","Aston Martin",78),("Pierre Gasly","Alpine",84),("Esteban Ocon","Alpine",83),("Nico Hulkenberg","Haas",83),("Kevin Magnussen","Haas",80),("Yuki Tsunoda","RB",82),("Daniel Ricciardo","RB",81),("Alexander Albon","Williams",83),("Franco Colapinto","Williams",77),("Valtteri Bottas","Kick Sauber",80),("Zhou Guanyu","Kick Sauber",76))},
    2025: {"champion": "Lando Norris", "champion_team": "McLaren", "constructors_champion": "McLaren", "num_races": 24,
        "drivers": _D(("Lando Norris","McLaren",96),("Oscar Piastri","McLaren",95),("Max Verstappen","Red Bull",97),("Yuki Tsunoda","Red Bull",82),("Charles Leclerc","Ferrari",92),("Lewis Hamilton","Ferrari",91),("George Russell","Mercedes",90),("Andrea Kimi Antonelli","Mercedes",87),("Fernando Alonso","Aston Martin",86),("Lance Stroll","Aston Martin",77),("Pierre Gasly","Alpine",84),("Jack Doohan","Alpine",76),("Esteban Ocon","Haas",83),("Oliver Bearman","Haas",81),("Alexander Albon","Williams",84),("Carlos Sainz","Williams",88),("Isack Hadjar","RB",80),("Liam Lawson","RB",79),("Nico Hulkenberg","Kick Sauber",82),("Gabriel Bortoleto","Kick Sauber",78))},
}

# Iconic circuits pool for each era. We select a subset of size num_races.
CIRCUITS_BY_ERA = {
    (1950, 1969): ["Silverstone","Monaco","Indianapolis","Spa-Francorchamps","Reims","Monza","Nurburgring","Zandvoort","Aintree","Sebring","Watkins Glen","East London","Riverside","Rouen","Mexico City","Kyalami","Clermont-Ferrand","Brands Hatch"],
    (1970, 1989): ["Kyalami","Jarama","Long Beach","Interlagos","Imola","Zolder","Monaco","Detroit","Montreal","Paul Ricard","Silverstone","Hockenheim","Osterreichring","Zandvoort","Monza","Estoril","Suzuka","Adelaide","Nurburgring"],
    (1990, 2005): ["Interlagos","Melbourne","Sepang","Sakhir","Imola","Barcelona","Monaco","Montreal","Nurburgring","Magny-Cours","Silverstone","Hockenheim","Hungaroring","Spa-Francorchamps","Monza","Indianapolis","Shanghai","Suzuka","Estoril","Adelaide","Buenos Aires","Kyalami","Istanbul"],
    (2006, 2025): ["Sakhir","Jeddah","Melbourne","Suzuka","Shanghai","Miami","Imola","Monaco","Barcelona","Montreal","Spielberg","Silverstone","Hungaroring","Spa-Francorchamps","Zandvoort","Monza","Baku","Marina Bay","Austin","Mexico City","Interlagos","Las Vegas","Losail","Yas Marina","Hockenheim","Nurburgring","Sochi","Istanbul","Paul Ricard","Portimao","Mugello","Sepang"],
}

def get_circuits_for_year(year: int, num: int):
    for (start, end), pool in CIRCUITS_BY_ERA.items():
        if start <= year <= end:
            # deterministic selection: take first num from pool (padded if needed)
            selected = []
            i = 0
            while len(selected) < num:
                selected.append(pool[i % len(pool)])
                i += 1
            return selected
    return ["Silverstone"] * num


def get_all_years():
    return sorted(SEASONS.keys())


def get_season(year: int):
    return SEASONS.get(year)
